---
title: "MUSA 5080 Portfolio"
---

# Welcome to My Portfolio

This portfolio documents my learning journey in Public Policy Analytics (CPLN 5920).

## About This Course
Advanced spatial analysis and data science for urban planning and public policy.

## Portfolio Structure
- **Weekly Notes:** My learning reflections and key concepts
- **Labs:** Completed assignments and analyses
- **Final Project:** Capstone modeling challenge

## About Me
Before coming to graduate school, I studied human geography at West Virginia University where I focused my coursework on development studies, political ecology, and economics. While in undergrad, I worked for Enterprise Community Partners, where I interned on their advisory team and developed my interest affordable housing and economic development.

I'm taking this course in order to develop my skills as a quantitative policy analyst. I am interested in housing policy and development, and hope to apply the skills I learn in this course to answering questions surrounidng housing affordability and equity.

## Contact
- Email: harner1@design.upenn.edu
- GitHub: @EthanHarner02
